/* formats.js — turn cues + style into SRT, WebVTT and ASS.
 *
 * ASS (Advanced SubStation Alpha) is the one that carries your look — font,
 * size, colors, outline, position and (optionally) word-by-word karaoke — and
 * is what ffmpeg burns into video with libass. SRT/VTT are plain-text captions.
 */
(function () {
  const WXC = (window.WXC = window.WXC || {});

  const pad = (n, w) => String(Math.floor(n)).padStart(w, "0");

  function srtTime(t) {
    t = Math.max(0, t);
    const ms = Math.round((t - Math.floor(t)) * 1000);
    const s = Math.floor(t) % 60,
      m = Math.floor(t / 60) % 60,
      h = Math.floor(t / 3600);
    return `${pad(h, 2)}:${pad(m, 2)}:${pad(s, 2)},${pad(ms, 3)}`;
  }
  function vttTime(t) {
    return srtTime(t).replace(",", ".");
  }
  function assTime(t) {
    t = Math.max(0, t);
    const cs = Math.round((t - Math.floor(t)) * 100);
    const s = Math.floor(t) % 60,
      m = Math.floor(t / 60) % 60,
      h = Math.floor(t / 3600);
    return `${h}:${pad(m, 2)}:${pad(s, 2)}.${pad(cs, 2)}`;
  }

  // ---------- SRT ----------
  function toSRT(cues) {
    return (
      cues
        .map(
          (c, i) =>
            `${i + 1}\n${srtTime(c.start)} --> ${srtTime(c.end)}\n${c.text}\n`
        )
        .join("\n") + "\n"
    );
  }

  // ---------- WebVTT ----------
  function toVTT(cues, karaoke) {
    let out = "WEBVTT\n\n";
    cues.forEach((c, i) => {
      out += `${i + 1}\n${vttTime(c.start)} --> ${vttTime(c.end)}\n`;
      if (karaoke && c.words && c.words.length) {
        out +=
          c.words
            .map((w, j) => (j === 0 ? "" : `<${vttTime(w.start)}>`) + escapeVTT(w.word))
            .join(" ") + "\n\n";
      } else {
        out += c.text + "\n\n";
      }
    });
    return out;
  }
  const escapeVTT = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

  // ---------- ASS ----------
  // hex "#rrggbb" + alpha 0..1 (1 = opaque)  ->  &HAABBGGRR
  function assColor(hex, alpha) {
    const h = hex.replace("#", "");
    const r = h.slice(0, 2),
      g = h.slice(2, 4),
      b = h.slice(4, 6);
    const a = pad(Math.round((1 - (alpha == null ? 1 : alpha)) * 255).toString(16).padStart(2, "0"), 2);
    return `&H${a}${b}${g}${r}`.toUpperCase();
  }
  const alignMap = {
    "bottom-left": 1, "bottom-center": 2, "bottom-right": 3,
    "middle-left": 4, "middle-center": 5, "middle-right": 6,
    "top-left": 7, "top-center": 8, "top-right": 9,
  };
  function escapeASS(s) {
    return s.replace(/\\/g, "\\\\").replace(/\{/g, "\\{").replace(/\}/g, "\\}").replace(/\n/g, "\\N");
  }

  // style = the app's style object; playH is the reference height the font size
  // was authored against (1080). Everything scales with the target video.
  function toASS(cues, style, opts) {
    const o = Object.assign({ karaoke: true, playW: 1920, playH: 1080 }, opts);
    const align = alignMap[`${style.vAlign}-${style.hAlign}`] || 2;
    const marginX = Math.round((style.marginX / 100) * o.playW);
    const marginY = Math.round((style.marginY / 100) * o.playH);
    const boxStyle = style.boxOpacity > 0.02 ? 3 : 1; // 3 = opaque box, 1 = outline+shadow
    const primary = assColor(style.active, 1); // filled (karaoke sweep foreground)
    const secondary = assColor(style.color, 1); // unfilled
    const outline = assColor(style.strokeColor, 1);
    const back = boxStyle === 3 ? assColor(style.box, style.boxOpacity) : assColor(style.shadowColor, 1);

    const header =
`[Script Info]
; Generated by WhisperX Caption Studio — https://github.com/zeerebel/whisperx_caption
ScriptType: v4.00+
PlayResX: ${o.playW}
PlayResY: ${o.playH}
WrapStyle: 2
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Caption,${(style.fontName || style.font).replace(/,.*$/, "").replace(/['"]/g, "")},${Math.round(style.size)},${primary},${secondary},${outline},${back},${style.weight >= 700 ? -1 : 0},0,0,0,100,100,${style.tracking},0,${boxStyle},${style.stroke},${style.shadow},${align},${marginX},${marginX},${marginY},1

[Events]
Format: Layer, Start, End, Style, MarginL, MarginR, MarginV, Effect, Text
`;

    const useK = o.karaoke && cues.some((c) => c.words && c.words.length);
    const lines = cues.map((c) => {
      let text;
      if (useK && c.words && c.words.length) {
        text = c.words
          .map((w, j) => {
            const next = c.words[j + 1];
            const holdUntil = next ? next.start : w.end;
            const cs = Math.max(1, Math.round((holdUntil - w.start) * 100));
            return `{\\kf${cs}}${escapeASS(w.word)}${j < c.words.length - 1 ? " " : ""}`;
          })
          .join("");
      } else {
        text = escapeASS(c.text);
      }
      return `Dialogue: 0,${assTime(c.start)},${assTime(c.end)},Caption,,0,0,0,,${text}`;
    });
    return header + lines.join("\n") + "\n";
  }

  // A styled config sidecar (handy to re-open or feed another tool)
  function toJSON(cues, style) {
    return JSON.stringify(
      { v: 1, generator: "whisperx_caption", style, cues: cues.map((c) => ({ start: +c.start.toFixed(3), end: +c.end.toFixed(3), text: c.text, words: c.words })) },
      null,
      2
    );
  }

  WXC.formats = { toSRT, toVTT, toASS, toJSON, srtTime, vttTime, assTime, assColor };
})();
